### ISSUE TITLE
add PowerShell env support

### ISSUE THREAD

**Issue by vvuk** [juj/emsdk#100]
PowerShell is the new default shell for Windows 10, and it would be nice if emsdk could generate the proper env for it.

PowerShell syntax (in a `emsdk_set_env.ps1` file) would look like:
```
$env:PATH = "C:\proj\emsdk;$env:PATH"
$env:EMSDK = "C:\proj\emsdk"
```
etc.

**Comment by juj** [comment]
That would make sense. Does `cmd.exe /c '\my-app\my-file.bat'` serve as a workaround in the meanwhile? (https://stackoverflow.com/questions/20645326/safest-way-to-run-bat-file-from-powershell-script)

**Comment by vvuk** [comment]
Unfortunately no, because that doesn't modify the current environment.

**Comment by juj** [comment]
@SaschaNaz contributed PowerShell support, merged in above commit. @vvuk let me know if that has any issues, or if this can be closed as resolved?

**Comment by yume-chan** [comment]
The `emsdk.ps1` doesn't work for me, the error from PowerShell is:

>& : The term 'emsdk_set_env.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
>At C:\Users\Simon\emsdk\emsdk.ps1:33 char:7
>+&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;& emsdk_set_env.ps1
>+&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;~~~~~~~~~~~~~~~~~
>&nbsp;&nbsp;&nbsp;&nbsp;+ CategoryInfo          : ObjectNotFound: (emsdk_set_env.ps1:String) [], CommandNotFoundException
>&nbsp;&nbsp;&nbsp;&nbsp;+ FullyQualifiedErrorId : CommandNotFoundException

Actually, this line:

https://github.com/juj/emsdk/blob/00e8d9df957006f2d6e23b75aa58c7ffc48c456c/emsdk.ps1#L33

Should be `& ./emsdk_set_env.ps1`.

**Comment by saschanaz** [comment]
Calling script file does not require `./` at least on Windows, which Powershell version / OS are you using?

**Comment by saschanaz** [comment]
Oops, it worked for me because I added the path as a system path. Sorry.

**Comment by saschanaz** [comment]
Opened #114.
