### ISSUE TITLE
error occurs when execute "./emsdk install sdk-incoming-64bit binaryen-master-64bit"

### ISSUE THREAD

**Issue by tsangint** [juj/emsdk#102]
Running build: ['make', '-j1']
Scanning dependencies of target LLVMDemangle
[  0%] Building CXX object lib/Demangle/CMakeFiles/LLVMDemangle.dir/ItaniumDemangle.cpp.o
[  0%] Linking CXX static library ../libLLVMDemangle.a
[  0%] Built target LLVMDemangle
Scanning dependencies of target LLVMSupport
[  0%] Building CXX object lib/Support/CMakeFiles/LLVMSupport.dir/APFloat.cpp.o
[  0%] Building CXX object lib/Support/CMakeFiles/LLVMSupport.dir/APInt.cpp.o
[  0%] Building CXX object lib/Support/CMakeFiles/LLVMSupport.dir/APSInt.cpp.o
[  0%] Building CXX object lib/Support/CMakeFiles/LLVMSupport.dir/ARMBuildAttrs.cpp.o
[  0%] Building CXX object lib/Support/CMakeFiles/LLVMSupport.dir/ARMWinEH.cpp.o
[  0%] Building CXX object lib/Support/CMakeFiles/LLVMSupport.dir/Allocator.cpp.o
[  0%] Building CXX object lib/Support/CMakeFiles/LLVMSupport.dir/BlockFrequency.cpp.o
[  0%] Building CXX object lib/Support/CMakeFiles/LLVMSupport.dir/BranchProbability.cpp.o
[  0%] Building CXX object lib/Support/CMakeFiles/LLVMSupport.dir/CachePruning.cpp.o
[  0%] Building CXX object lib/Support/CMakeFiles/LLVMSupport.dir/circular_raw_ostream.cpp.o
[  0%] Building CXX object lib/Support/CMakeFiles/LLVMSupport.dir/Chrono.cpp.o
[  0%] Building CXX object lib/Support/CMakeFiles/LLVMSupport.dir/COM.cpp.o
[  0%] Building CXX object lib/Support/CMakeFiles/LLVMSupport.dir/CommandLine.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
lib/Support/CMakeFiles/LLVMSupport.dir/build.make:350: recipe for target 'lib/Support/CMakeFiles/LLVMSupport.dir/CommandLine.cpp.o' failed
make[2]: *** [lib/Support/CMakeFiles/LLVMSupport.dir/CommandLine.cpp.o] Error 4
CMakeFiles/Makefile2:302: recipe for target 'lib/Support/CMakeFiles/LLVMSupport.dir/all' failed
make[1]: *** [lib/Support/CMakeFiles/LLVMSupport.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
Build failed due to exception!
Working directory: /home/ubuntu/workspace/emsdk/clang/fastcomp/build_incoming_64
Command '['make', '-j1']' returned non-zero exit status 2
Installation failed!

**Comment by tsangint** [comment]
It's because of lack of memory.I resolved it by swap.

sudo dd if=/dev/zero of=/swapfile bs=64M count=16
sudo mkswap /swapfile
sudo swapon /swapfile

**Comment by juj** [comment]
Glad you were able to figure it out. Yikes that running out of memory can end up in internal compiler error :/ That can be hard to debug..
