### ISSUE TITLE
cmake version issues using emsdk portable on Travis CI

### ISSUE THREAD

**Issue by dcodeIO** [juj/emsdk#108]
A few weeks ago, one of my emsdk based builds broke on Travis CI with `CMake 3.4.3 or higher is required.  You are running version 3.2.2`.

The exact same setup worked before: I am [installing a newer cmake version manually and adding it to path](https://github.com/AssemblyScript/binaryen.js/blob/master/.travis.yml#L24).
https://travis-ci.org/AssemblyScript/binaryen.js/builds/290105263#L498

Though, the error persists:
https://travis-ci.org/AssemblyScript/binaryen.js/builds/290105263#L507

Any ideas?

**Comment by juj** [comment]
The requirement of CMake 3.4.3 or newer is/was indeed the correct one. It was incorporated in this commit: https://github.com/kripken/emscripten/commit/a151ef1485, and first appeared in Emscripten version 1.36.8. This requirement is carried over from LLVM CMake script, which after we updated to LLVM 3.9, requires CMake 3.4.3, so we added it as a requirement to Emscripten's CMake script as well.

Now in hindsight I realize that it would be possible for developers to use a precompiled LLVM version (that was compiled with a new CMake), but keep using an older CMake version to build their own projects. Pushed a fix that resets our minimum required version to CMake 3.0.0. (we did not have a minimum required version directive before the 3.4.3). That should make Travis CI integrations easier. Does that help?

**Comment by dcodeIO** [comment]
Just tried it, but unfortunately it still does not work.

In my setup, there are two cmake versions. Travis's trusty cmake (3.2.2) and one I download and add to path (3.4.3, also tried newer versions). Though the second one is in path, it seems that one of the build scripts resorts to system cmake.

Right before installation, I do a `cmake --version`, which uses the correct cmake from PATH:

```
cmake version 3.4.3
CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

But in the next step, this happens:

```
Cloning into '/home/travis/emsdk-portable/clang/fastcomp/src'...
Checking out files: 100% (21813/21813), done.
Already up-to-date.
Cloning into '/home/travis/emsdk-portable/clang/fastcomp/src/tools/clang'...
Already up-to-date.
CMake Error at CMakeLists.txt:3 (cmake_minimum_required):
 CMake 3.4.3 or higher is required. You are running version 3.2.2
```

The strange thing is that this exact setup, that is adding a newer cmake to path, worked fine a couple of weeks ago, but then suddenly stopped working.
