### ISSUE TITLE
emsdk broken on emscripten CI

### ISSUE THREAD

**Issue by kripken** [juj/emsdk#127]
Output contains
```
Done installing SDK 'sdk-1.37.27-64bit'.
Writing .emscripten configuration file to user home directory /root/
Traceback (most recent call last):
  File "./emsdk", line 2327, in <module>
    sys.exit(main())
  File "./emsdk", line 2266, in main
    tools_to_activate = set_active_tools(tools_to_activate, permanently_activate=permanently_activate)
NameError: global name 'permanently_activate' is not defined
Exited with code 1
```
e.g. https://travis-ci.org/kripken/emscripten/jobs/325116977

**Comment by kripken** [comment]
Seems to have broken in https://github.com/juj/emsdk/commit/326606f5aa95460a7c28b16c856e9ff5aabeb8f7

**Comment by kripken** [comment]
lol this made Broken Code Bot https://twitter.com/brokencodebot/status/948969893495558145

**Comment by juj** [comment]
Oops, fixed in https://github.com/juj/emsdk/commit/359b72dbb5f92ab6c6c4d7f13823997e07e2131f
