### ISSUE TITLE
inconsistent build doc & config

### ISSUE THREAD

**Issue by wothke** [juj/emsdk#129]
I had recently installed the prebuilt 1.37.9 (Win10 portable) from this repository. (Earler I had fetched the respective "latest" version from the emscripten repository - until I noticed that that that version is unusable due to the outdated Java version that comes with it..)

Unfortunately I then found that I actually need 1.37.29 in order to use wasm. So I tried to follow the emsdk README.md instructions to build that version from source. Which brings me to the first issue:

1) For somebody like me - who only used the prebuilt stuff so far - the documentation is pretty useless - because it DOES NOT say what toolchain is needed as a prerequisite to build from source: I wasted hours to download "Visual Studio 2010" (which is advertised in the emscripten docs) - just to find that that shit does NOT work - nor does the respective "Express" version. I finally installed the "Visual Studio 2015 Community edition" - and another half a day later that now at least seems to compile the stuff (i.e. "emsdk install sdk-tag-1.37.29-64bit" successfully completed..). Please update the README.md and explain what toolchain is needed before emsdk can be used to build from source.. (and where to get it..)

2) After having wasted all that time I finally have a 1.37.29 built from source. And it seems I am back to the same shitty "Unsupported major.minor version 52.0" problem.. WTF?! (as a workaround I just copied a jre1.8.151 into the respective folder and that seems to fix the Java version issue.. ) but please: fix the inconsistent 1.37.29 baseline!

**Comment by juj** [comment]
Sorry that you wasted time. Emsdk 1.37.23 and newer should come with jre1.8.151.

**Comment by wothke** [comment]
np, thanks!
