### ISSUE TITLE
VS2017 suppport

### ISSUE THREAD

**Issue by a2kas** [juj/emsdk#180]
Is it supporting for VS2017? if yes,I need just install emsdk and Emscripten will appear in VS2017 configuration manager?

**Comment by juj** [comment]
Visual Studio integration is unfortunately not supported in any Visual Studio version. (There was an ancient plugin tool for Visual Studio 2010, but that has been discontinued). I'll close this as unsupported; if someone is able to contribute a plugin, there may be a number of users out there who would like to use it as well.
