### ISSUE TITLE
Building RelWithDebInfo bloats build artifacts and slows down the build

### ISSUE THREAD

**Issue by cosinusoidally** [juj/emsdk#19]
I recently installed the Emscripten SDK on my 64 bit Ubuntu 14.04 machine using the emsdk tool. Looking at the source of emsdk, it appears that you build the release version of clang/llvm with debug symbols turned on (https://github.com/juj/emsdk/blob/master/emsdk#L444). On my machine this caused in excess of 3GB of build artifacts to be created. Unfortunately I am fairly low on disk space, so this exhausted all the available disk space on my machine and caused the build to fail.

I did manage to build from the sdk by modifying the emsdk to build without debug symbols (-DCMAKE_BUILD_TYPE=Release). This reduced the disk usage by about a factor of 10 (down to about 400MB).

**Comment by dreamlayers** [comment]
I see that now build type is part of `emsdk_manifest.json`, with `Release` specified for master and `RelWithDebInfo` for incoming. I agree this makes sense, but I wish I could override it from the command line.

**Comment by juj** [comment]
That sounds sensible. I'll try to squeeze in an option for this for the next emsdk release.

**Comment by juj** [comment]
This override now exists in the form of `--build=type` option, see the above commit. Note however that this is rather delicate, and will require passing the same override to both emsdk `install` and `activate` steps, as well as `emsdk_env` and `emcmdprompt` scripts if using those scripts.

**Comment by dreamlayers** [comment]
Thanks! After getting emsdk from this repository, I was able to build with `./emsdk install clang-incoming-64bit --build=release`. Lowercase is required for the build type; [I added a comment about this](https://github.com/juj/emsdk/commit/1170e55abd7f0fe01e63908ee08b1d481d958a23#commitcomment-10652360).

It seems `--build=type` is only needed for `install` when not in Windows.
