### ISSUE TITLE
Doc bug: Debian node.js package has wrong symlink

### ISSUE THREAD

**Issue by floooh** [juj/emsdk#20]
Hi, I had a little WTF moment today wenn I setup a fresh Linux machine. Debian has decided to rename the nodejs executable to 'nodejs' since it collides with another package ('node'). The emscripten SDK expects 'node' of course.

There's a separate package now called 'nodejs-legacy'. Despite being called 'legacy' this still contains the latest node.js, but has the old symlink set called 'node'.

May be there should be a little note in the documentation about this. It cost me some time because I thought that the nodejs-legacy package would contain an old version of node.js.

Silly Debians...

**Comment by juj** [comment]
Thinking about this, I'm leaning on that on linux, we should just always first search for `which nodejs`, and if that exists, then use that as node, and if not, then use `node`. Can anyone think of a reason that could fail?

**Comment by floooh** [comment]
Sounds good to me. This doesn't solve the confusing problem with the Debian package naming (node vs nodejs), but at least the right executable would be called without setting a link.
