### ISSUE TITLE
Where is binaryen's wasm.js

### ISSUE THREAD

**Issue by erikaemma** [juj/emsdk#206]
I study emsdk by https://developer.mozilla.org/zh-CN/docs/WebAssembly/C_to_wasm, when I run `./emsdk install --build=Release sdk-incoming-64bit binaryen-master-64bit` on my Ubuntu 16.04, it fail at binaryen's final setup 100%:
No such file or directory: binaryen/master/bin/wasm.js

**Comment by kripken** [comment]
Thanks! Looks like I broke this when I removed wasm.js, as I didn't realize the emsdk had it hardcoded. Fix in https://github.com/juj/emsdk/pull/207
