### ISSUE TITLE
Support VS2013

### ISSUE THREAD

**Issue by Mischanix** [juj/emsdk#23]
I didn't feel like installing VS2010, so [here's my hacks to make it work with VS2013](https://github.com/Mischanix/emsdk/compare/juj:master...master).  I'll add, after having read kripken/emscripten#1697, I don't care about the plugins, since I don't use the Visual Studio IDE.  I just wanted to be able to run VS2013 cl/link and this simple modification seems to accomplish that.  I did experience an issue that the resulting clang binaries weren't copied to the clang/e[version] directory and LLVM_ROOT wasn't added to my .emscripten config but I'm not sure why the file copy is not being performed in Python and don't have the time to figure out where it's supposed to be done.

**Comment by juj** [comment]
Currently emsdk requires VS2013, so this is resolved. We are looking at supporting VS2015 soon.

**Comment by NiteLordz** [comment]
Is there a vs-tool plugin that works on VS 2013 ?

**Comment by juj** [comment]
I don't know of a version of vs-tool that would work on VS2012 or up. The tool was a bit experimental in nature, and its development has mostly been dropped now. I'm not sure if there exists a contributor who might have kept it alive.

**Comment by Maxmaxmaximus** [comment]
Visual Studio 2015? no? look to calendar)
