### ISSUE TITLE
Emsdk single threaded

### ISSUE THREAD

**Issue by w-vi** [juj/emsdk#28]
Using emsdk to get the latest emscripten is wicked but i miss one feature which I need when using emsdk in CI environment where there are limited resources. I haven't found how to tell emsdk when running `install` not build on as much as possible cores but to enforce certain number. In the CI I'd like to set it to one, I don't mind that it takes ages, It's being done once in a while only. Currently I have solved it by having a env var modified the emsdk to check for it in `make_build` function to set it directly. Is there a better solution, is somebody else interested in such patch?

**Comment by juj** [comment]
I think adding a `-jX` option (as is standard for `make` as well) would be ok. I can do that for next release, or if you want to submit a pull request, feel free. In general we have not had environment variables used for setting options in emsdk, so I think a cmdline option would be better here. Does that sound equivalent to you?

**Comment by w-vi** [comment]
`-jx` would be the best ... the environment variable was the quickest workaround hack, I didn't need to touch almost any code. I can submit a PR once I get to fix it properly. This week I'm busy but the next I'll have some time.

**Comment by juj** [comment]
No worries, I implemented this in the above commit.

**Comment by w-vi** [comment]
wicked! :+1:
