### ISSUE TITLE
Inconsistency between OS X and Linux: emsdk list provides different sets of SDK versions

### ISSUE THREAD

**Issue by michaKFromParis** [juj/emsdk#34]
Hi!

Thanks for the great work as I included emsdk for a while in our build scripts and ci with much satisfaction. I bumped into an inconsistency in between OS X and Linux though.
Performing **emsdk list** on Linux and OS X give different sets of SDK version.
I am targeting a specific Emscripten SDK (**1.29.0**) as 1.30.0 does not provide a working -g4 debuggable source map yet in my configuration.

Under OSX, no pb, I can easily pick 1.29 with the following commands:

```bash
EmscriptenVersion='1.29.0'
./emsdk update
./emsdk install "emscripten-$EmscriptenVersion"
./emsdk install "sdk-$EmscriptenVersion"
./emsdk activate "emscripten-$EmscriptenVersion"
```

But on Linux, the only available versions of clang and the SDK are **master** and **incoming** (see the **emsdk list** output below)

Is this something normal?
What would be your suggestion to align the SDK versions across OS / machines ?

Thanks

OSX:

```bash
./emsdk list

The following individual tools exist:
           clang-incoming-32bit
           clang-incoming-64bit
           clang-master-32bit
           clang-master-64bit
    (*)    clang-e1.29.0-64bit      	INSTALLED
           clang-e1.30.0-64bit
           node-0.12.2-64bit
           spidermonkey-37.0.1-64bit
           spidermonkey-nightly-2015-04-12-64bit
    (*)    emscripten-1.29.0        	INSTALLED
           emscripten-1.30.0
           emscripten-incoming-32bit
           emscripten-master-32bit
           emscripten-incoming-64bit
           emscripten-master-64bit
           crunch-1.04

The following Emscripten SDK versions are available:
         sdk-incoming-64bit
         sdk-master-64bit
    *    sdk-1.29.0-64bit         	INSTALLED
         sdk-1.30.0-64bit
```

Linux:

```bash
./emsdk list

The following individual tools exist:
           clang-incoming-32bit
           clang-incoming-64bit
           clang-master-32bit
    (*)    clang-master-64bit       	INSTALLED
           emscripten-1.29.0        	INSTALLED
           emscripten-1.30.0
           emscripten-incoming-32bit
           emscripten-master-32bit
           emscripten-incoming-64bit
    (*)    emscripten-master-64bit  	INSTALLED


The following Emscripten SDK versions are available:
         sdk-incoming-32bit
         sdk-incoming-64bit
         sdk-master-32bit
    *    sdk-master-64bit         	INSTALLED
```

**Comment by michaKFromParis** [comment]
Hi there. Just bumping this issue. Anyone has a clue?

**Comment by juj** [comment]
The numbered Emscripten/SDK versions are currently only for precompiled versions. The incoming and master versions are built from source. We don't ship precompiled binaries for Linux, only on OSX and Windows, so therefore the numbered versions are not available.

There has been talk about adding support for building git tags (and even specific commits) directly via emsdk. I believe that would give you the abililty to build specific tagged version from source?

**Comment by michaKFromParis** [comment]
Hi,

Thanks for your reply. I had to switch to incoming to have the SDL port building correctly anyway so I guess all my nodes are on the same page for now but you got my point really well. We need to be able to guarantee the version of the SDK you build against.
So yes, building tagged revisions (or more generally) any git commit would be awesome.
Would be happy to help if I wasn't so busy at the moment.

M

**Comment by juj** [comment]
Let me reopen to track this until this is implemented.

**Comment by michaKFromParis** [comment]
Cool! I'm very happy with the incoming build at the moment. Everything works like a charm on my side both under Linux and OS X but it will only be true until it breaks. Thanks!

**Comment by juj** [comment]
The new Emscripten SDK 1.34.1 released today now offers support for building from tags, see https://mail.google.com/mail/u/0/#label/Emscripten-discuss/14e54d9fe06a5180

**Comment by michaKFromParis** [comment]
Great Job!

I'll integrate it soon and will let you know if I run into any troubles.

Thanks
