### ISSUE TITLE
Manifest error: No tool by name 'clang-tag-1.34.1-64bit' found!

### ISSUE THREAD

**Issue by luxe** [juj/emsdk#37]
After downloading the latest release of Emscripten for Linux, I followed the steps [here][1]  
```
$ ./emsdk update
Downloading: /home/malko/Desktop/emsdk_portable/zips/emsdk_unix_update.tar.gz from https://s3.amazonaws.com/mozilla-games/emscripten/packages/emsdk_unix_update.tar.gz
Unpacking '/home/malko/Desktop/emsdk_portable/zips/emsdk_unix_update.tar.gz' to '/home/malko/Desktop/emsdk_portable'
emsdk_portable/emscripten-tags.txt
emsdk_portable/emsdk
emsdk_portable/emsdk_env.sh
emsdk_portable/emsdk_manifest.json
emsdk_portable/README.md
Fetching all tags from Emscripten Github repository...
Done. 36 tagged releases available, latest is 1.34.1.
```
==========
```
$ ./emsdk install latest 
Installing SDK 'sdk-tag-1.34.1-64bit'..
Manifest error: No tool by name 'clang-tag-1.34.1-64bit' found! This may indicate an internal SDK error!
Traceback (most recent call last):
  File "./emsdk", line 1734, in <module>
    sys.exit(main())
  File "./emsdk", line 1717, in main
    success = tool.install()
  File "./emsdk", line 1007, in install
    success = tool.install()
AttributeError: 'NoneType' object has no attribute 'install'
```

I was told [here][2], that this may be an SDK related issue?  

[1]: http://kripken.github.io/emscripten-site/docs/getting_started/downloads.html
[2]: https://github.com/kripken/emscripten/issues/3607

**Comment by GGAlanSmithee** [comment]
Im also getting this. Works when I do ./emsdk install <version> though

When typing ./emsdk list, I see that there is an "e" in all of the clang version numbers, which makes it differ from the name that is being looked for according to the output error.

This might be how it should be, or totalt unrelated, first time trying to install emscripten here.

**Comment by GGAlanSmithee** [comment]
Heh, github thought I was trying to inject som script or something and removed my unintended HTML tag.

I meant to say that it works when I typer ./emsdk install version where version is one of the versions listed

**Comment by cliffordwolf** [comment]
I am also experiencing this error. Ubuntu 14.04 LTS. This is on a system that worked with "emsdk install latest" fine on June 20th. I've also tried it in a freshly installed VM just to make sure that it is nothing wrong with my main installation. In both cases I get:

    emsdk_portable$ ./emsdk install latest
    Installing SDK 'sdk-tag-1.34.1-64bit'..
    Manifest error: No tool by name 'clang-tag-1.34.1-64bit' found! This may indicate an internal SDK error!
    Traceback (most recent call last):
      File "./emsdk", line 1734, in <module>
        sys.exit(main())
      File "./emsdk", line 1717, in main
        success = tool.install()
      File "./emsdk", line 1007, in install
        success = tool.install()
    AttributeError: 'NoneType' object has no attribute 'install'

**Comment by GGAlanSmithee** [comment]
Found kripken/emscripten#3601 and #36 which explains the bug and submits a PR for it

**Comment by cliffordwolf** [comment]
It's even already merged. Someone should really update

https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz

As it is it is practically unusable for all 64 bit Linux users.

Hotfix:

    rm emsdk_manifest.json
    wget https://raw.githubusercontent.com/juj/emsdk/master/emsdk_manifest.json

**Comment by juj** [comment]
Thanks for catching this, and very sorry about the typo! Updated packages are now pushed and they should fix the Linux issue.
