### ISSUE TITLE
emsdk doesn't support 32-bit systems

### ISSUE THREAD

**Issue by mlimber** [juj/emsdk#39]
I see that 32-bit support was dropped as of 1.16. I'd like to see that brought back because some of my customers are stuck on 32-bit OSes. I may be willing to contribute the code to do it depending on what's involved, but perhaps it was dropped because of issues that I am not aware of.

Is it worth adding it back?

Specifically, the error message I get on Windows is:

> This version of [...]\emscripten\python\2.7.5.3_64bit\python.exe is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher.

On the face of it, this doesn't seem like it would be a lot of work to adapt to a 32-bit system -- replace the x64 Python with x86 Python. (And so on for node, clang, etc.)

**Comment by juj** [comment]
Let's focus the discussion on the other tracker where the conversation is more recent.
