### ISSUE TITLE
emscriten-only option when `activate --global`?

### ISSUE THREAD

**Issue by SaschaNaz** [juj/emsdk#55]
`emsdk activate --global emscripten-1.35.0` activates all tools including node.js. I hope I can only register emscripten tools (emcc, etc...) to system path and not node.js, as I already have a newer version of node.js.  Is there a related command line option? Should I just uninstall emscripten-bundled one?

**Comment by juj** [comment]
Hmm, there is no specific deactivation command, but emsdk looks at the configuration file for what is activated. Try deleting the configuration file `$HOME\.emscripten` and then run `emsdk activate --global emscripten-1.35.0`. I think that should do what you want.

**Comment by SaschaNaz** [comment]
I tried deleting `.emscripten` file but after `emsdk activate emscripten-incoming-64bit --global` the emsdk revived it:

```
PS C:\WINDOWS\system32> emsdk activate emscripten-incoming-64bit --global
Registering active Emscripten environment globally for all users.

Writing .emscripten configuration file to user home directory C:\Users\sasch/
The Emscripten configuration file C:\Users\sasch\.emscripten has been rewritten with the following contents:

import os
LLVM_ROOT='C:/Program Files/Emscripten/clang/e1.35.0_64bit'
EMSCRIPTEN_NATIVE_OPTIMIZER='C:/Program Files/Emscripten/clang/e1.35.0_64bit/optimizer.exe'
NODE_JS='C:/Program Files/Emscripten/node/4.1.1_64bit/bin/node'
PYTHON='C:/Program Files/Emscripten/python/2.7.5.3_64bit/python.exe'
JAVA='C:/Program Files/Emscripten/java/7.45_64bit/bin/java.exe'
EMSCRIPTEN_ROOT='C:/Program Files/Emscripten/emscripten/incoming'
EMSCRIPTEN_NATIVE_OPTIMIZER='C:/Program Files/Emscripten/emscripten/incoming_64bit_optimizer/RelWithDebInfo/optimizer.ex
e'
SPIDERMONKEY_ENGINE = ''
V8_ENGINE = ''
TEMP_DIR = 'c:/users/sasch/appdata/local/temp'
COMPILER_ENGINE = NODE_JS
JS_ENGINES = [NODE_JS]

Adding directories to PATH:
PATH += C:\Program Files\Emscripten\clang\e1.35.0_64bit
PATH += C:\Program Files\Emscripten\node\4.1.1_64bit\bin
PATH += C:\Program Files\Emscripten\java\7.45_64bit\bin

Setting environment variables:
EM_CONFIG = C:\Users\sasch\.emscripten
JAVA_HOME = C:\Program Files\Emscripten\java\7.45_64bit

PS C:\WINDOWS\system32>
```

**Comment by juj** [comment]
Oh, I am able to reproduce. Fixed this in https://github.com/juj/emsdk/commit/1dbfc85f1651680772f3b843accfafaf5ff1fc23. Try applying that change, and then delete the `.emscripten` file.

**Comment by SaschaNaz** [comment]
I manually copy-pasted emsdk from master branch and still saw this:

```
PS C:\WINDOWS\system32> emsdk activate sdk-tag-1.36.11-64bit --vs2015 --global
Registering active Emscripten environment globally for all users.

Writing .emscripten configuration file to user home directory C:\Users\sasch/
The Emscripten configuration file C:\Users\sasch\.emscripten has been rewritten with the following contents:

import os
LLVM_ROOT='C:/Program Files/Emscripten/clang/tag-e1.36.11/build_tag-e1.36.11_vs2015_64/RelWithDebInfo/bin'
NODE_JS='C:/Program Files/Emscripten/node/4.1.1_64bit/bin/node'
PYTHON='C:/Program Files/Emscripten/python/2.7.5.3_64bit/python.exe'
JAVA='C:/Program Files/Emscripten/java/7.45_64bit/bin/java.exe'
EMSCRIPTEN_ROOT='C:/Program Files/Emscripten/emscripten/tag-1.36.11'
EMSCRIPTEN_NATIVE_OPTIMIZER='C:/Program Files/Emscripten/emscripten/tag-1.36.11_vs2015_64bit_optimizer/RelWithDebInfo/op
timizer.exe'
SPIDERMONKEY_ENGINE = ''
V8_ENGINE = ''
TEMP_DIR = 'c:/users/sasch/appdata/local/temp'
COMPILER_ENGINE = NODE_JS
JS_ENGINES = [NODE_JS]

Adding directories to PATH:
PATH += C:\Program Files\Emscripten\clang\tag-e1.36.11\build_tag-e1.36.11_vs2015_64\RelWithDebInfo\bin
PATH += C:\Program Files\Emscripten\node\4.1.1_64bit\bin
PATH += C:\Program Files\Emscripten\java\7.45_64bit\bin
PATH += C:\Program Files\Emscripten\emscripten\tag-1.36.11

Setting environment variables:
EM_CONFIG = C:\Users\sasch\.emscripten
JAVA_HOME = C:\Program Files\Emscripten\java\7.45_64bit
EMSCRIPTEN = C:\Program Files\Emscripten\emscripten\tag-1.36.11

PS C:\WINDOWS\system32>
```

**Comment by juj** [comment]
> I manually copy-pasted emsdk from master branch and still saw this:

This is not guaranteed to work. The single file `emsdk` might not work in isolation with an older installed emsdk, depending on e.g. if it came from an earlier emsdk installer. It is best to bootstrap via `git clone https://github.com/juj/emsdk.git` if you want to use the master git version.

> PS C:\WINDOWS\system32> emsdk activate sdk-tag-1.36.11-64bit --vs2015 --global

This line is activating a whole SDK. The `sdk-tag-xxx` SDKs are defined here: https://github.com/juj/emsdk/blob/master/emsdk_manifest.json#L856, which are a combination of `["clang-tag-e%tag%-64bit", "node-4.1.1-64bit", "python-2.7.5.3-64bit", "java-7.45-64bit", "emscripten-tag-%tag%-64bit"]`. To just activate Emscripten, then call emsdk like the earlier line in this GitHub issue: `emsdk activate emscripten-incoming-64bit --global`, or similar.

The SDKs are aliases to collections of packages (https://github.com/juj/emsdk/blob/master/README.md#sdk-concepts) which all are required.

**Comment by SaschaNaz** [comment]
Ah, I was activating whole things. `emsdk activate emscripten-incoming-64bit --global` now works as expected, thanks :D
