### ISSUE TITLE
ArchLinux default python version is 3

### ISSUE THREAD

**Issue by krux02** [juj/emsdk#59]
I am very new to _WebAssembly_, I am just trying it out, and I have no Idea if you have more important things to do to fix this issue, so feel free to give it a low priority. It is no more than a little annoyance when developing on Arch based distributions.

The default python version on all Arch based linux distributions is currently python 3.5.2. Python 2 is available, but it has to be called with either _python2_ or _python2.7_, not just python meaning that the `#!/usr/bin/env python` directive in the python scripts will select the wrong version of python. I don't know if on other systems calling _python2_ or _python2.7_ will work, but when it does I would recommend to use that insdead of just _python_.

**Comment by birgersp** [comment]
Encountering the same problem here (using Manjaro)

**Comment by EXL** [comment]
+1

```
./emsdk install sdk-incoming-64bit binaryen-master-64bit  
Traceback (most recent call last):
  File "./emsdk", line 2108, in <module>
    sys.exit(main())
  File "./emsdk", line 1788, in main
    load_sdk_manifest()
  File "./emsdk", line 1563, in load_sdk_manifest
    expand_category_param('%tag%', emscripten_tags, t, is_sdk=False)
  File "./emsdk", line 1543, in expand_category_param
    for p, v in vars(t2).iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
```

**Comment by deltova** [comment]
+1 same error you should change the shebang for this script from python to python2

**Comment by juj** [comment]
> +1 same error you should change the shebang for this script from python to python2

That would fix the issue for Arch Linux, but break the script for OS X users, so that would not be good. In the latest commit `emsdk` has been improved to run on Python 3 as well (though has not been heavily tested), so let me close this as resolved.
