### ISSUE TITLE
LLVM build does not include WebAssembly backend

### ISSUE THREAD

**Issue by Maratyszcza** [juj/emsdk#65]
`emsdk` builds LLVM without the new WebAssembly backend, required for using `emcc` with `EMCC_WASM_BACKEND=1` option. To enable the WebAssembly backend, LLVM must be configured with `-DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD=WebAssembly`

**Comment by SaschaNaz** [comment]
It seems explicit parameter `--enable-wasm` will do it.
