### ISSUE TITLE
Update packages at "s3.amazonaws.com/mozilla-games/emscripten/packages" are outdated.

### ISSUE THREAD

**Issue by ImplOfAnImpl** [juj/emsdk#68]
For example, they don't contain this fix: "https://github.com/juj/emsdk/commit/01f5271887c65e4f84c9c631b4382f3beaa2dac0", which means that SDKs for the latest tags are not available on OSX and Linux (at least, not the 64-bit versions).

Also, the URL "http://clb.demon.fi/emscripten_dev/packages", which is used in the EMSDK_DEV mode, doesn't exist.

**Comment by juj** [comment]
We have migrated to autoupdating the builds to Amazon, so this is resolved.
