### ISSUE TITLE
Please add support for Visual Studio 2017 (vc141)

### ISSUE THREAD

**Issue by TooYoungTooSimp** [juj/emsdk#73]
Microsoft has released Visual Studio 2017 for a long time.
Please add support for Visual Studio 2017.

**Comment by floooh** [comment]
Btw, if you call cmake without an explicit generator (for instance "-G Visual Studio 15 Win64"), but instead with a platform name (e.g. "-A Win32" for 32-bit, or "-A x64" for 64-bit), cmake will automatically pick whatever Visual Studio version is installed. It also works with multiple Visual Studio installs, but I am not sure *which* version will be picked in this case (you could still use the --vs20xx command line arg to pick a specific VS version).

**Comment by TooYoungTooSimp** [comment]
I have looked through the file "emsdk". It can't recognize --vs2017, when I tried to manually modify the file(I know a little about python),it compiled,but some errors were reported.(sorry for my bad English)

**Comment by SaschaNaz** [comment]
Filed #77 for this.
