### ISSUE TITLE
info.module = HttpMime info.release = 4.2.5 info.timestamp = ${mvn.timestamp} # timestamp requires Maven 2.1

### ISSUE THREAD

**Issue by Amikarimi** [juj/emsdk#78]

**Comment by juj** [comment]
Perhaps this issue was entered to wrong repository?

**Comment by Amikarimi** [comment]
"status_read_color_picker" value="-13388315" />

**Comment by Amikarimi** [comment]
"status_read_color_picker" value="-13388315" />

**Comment by Amikarimi** [comment]
طری)</persianName><id>7688879</id><rate-avg>5.0</rate-avg><versionName>8.3</versionName><versionCode>22</versionCode><namespace>bluebrain.ovi.superchargerfreegdsz</namespace><inApp>0</inApp></app><app><price>5000</price><name>contact

**Comment by Amikarimi** [comment]
طری)</persianName><id>7688879</id><rate-avg>5.0</rate-avg><versionName>8.3</versionName><versionCode>22</versionCode><namespace>bluebrain.ovi.superchargerfreegdsz</namespace><inApp>0</inApp></app><app><price>5000</price><name>contact
