### ISSUE TITLE
Can't compile this on a debian/stretch VirtualBox 64bits guest

### ISSUE THREAD

**Issue by grondilu** [juj/emsdk#84]
Specifically, it always fails while trying to link clang (which happens at around 88% progression IIRC).

It's always either "memory exhausted", "bad alloc" or something like that.

I thought it was because my VM does not have much RAM, so I bought more RAM and gave my VM about 11Go.  Still fails.  In any case, when I follow memory usage with htop, it's clear the process fails much before all RAM is used.

I also tried with "gold" instead of "ld".  Still fails.

**Comment by phraemer** [comment]
Not sure why you are getting that. I have built it fine on Debian 9 in a VM with 4GB of memory.
Have you enough free disk space?

Precisely what steps are you taking?

**Comment by grondilu** [comment]
> Have you enough free disk space?

About 151Go available, according to `df -kh`.

> Precisely what steps are you taking?

Exactly those on http://webassembly.org/getting-started/developers-guide/:
```
$ git clone https://github.com/juj/emsdk.git
$ cd emsdk
$ ./emsdk install sdk-incoming-64bit binaryen-master-64bit
$ ./emsdk activate sdk-incoming-64bit binaryen-master-64bit

```
Though I can't go to step 4 (activate) since it's step 3 (install) that fails.

I'm going to try again with 4Go RAM and when it's done I'll post the exact error message I get.

Some system info:
```
$ uname -a
Linux stretch 4.9.0-3-686-pae #1 SMP Debian 4.9.30-2+deb9u1 (2017-06-18) i686 GNU/Linux
$ free -h
              total        used        free      shared  buff/cache   available
Mem:           4,0G        248M        3,3G         13M        402M        3,3G
Swap:          1,5G          0B        1,5G
$ gcc --version
gcc (Debian 6.3.0-18) 6.3.0 20170516
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
$ ld --version
GNU ld (GNU Binutils for Debian) 2.28
Copyright (C) 2017 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
```

**Comment by grondilu** [comment]
I've tried with a fresh new linux installation on an other VM.  That time compilation went through with 4Go.

So this may be either specific to debian or to my system which could be corrupted somehow.

I guess this issue can be closed since it's clear emsdk is not to blame.

**Comment by juj** [comment]
Some things that come to mind that you could try:

- force singlethreaded compilation (perhaps lots of parallel cores cause grief somehow?) via `emsdk -j1 install ...`

- try building debug or release

**Comment by gardner** [comment]
@grondilu it works for me in stretch: https://github.com/gardner/emsdk/blob/master/Dockerfile
