### ISSUE TITLE
Latest update causes argument must be string or number error

### ISSUE THREAD

**Issue by rajsite** [juj/emsdk#86]
A few hours ago we started seeing failures with the following error when performing `emsdk update` followed by `emsdk install sdk-1.37.9-64bit`.

You see an error:
```
Traceback (most recent call last):
  File "C:\projects\vireosdk\emscripten-sdk\\emsdk", line 2248, in <module>
    sys.exit(main())
  File "C:\projects\vireosdk\emscripten-sdk\\emsdk", line 2231, in main
    success = tool.install()
  File "C:\projects\vireosdk\emscripten-sdk\\emsdk", line 1283, in install
    success = tool.install()
  File "C:\projects\vireosdk\emscripten-sdk\\emsdk", line 1298, in install
    success = download_and_unzip(url, self.installation_path(), download_even_if_exists, filename_prefix=self.zipfile_prefix if hasattr(self, 'zipfile_prefix') else '')
  File "C:\projects\vireosdk\emscripten-sdk\\emsdk", line 904, in download_and_unzip
    dst_file = download_file(urljoin(emsdk_packages_url, zipfile), 'zips/', download_even_if_exists, filename_prefix)
  File "C:\projects\vireosdk\emscripten-sdk\\emsdk", line 453, in download_file
    file_size = get_content_length(u.info())
  File "C:\projects\vireosdk\emscripten-sdk\\emsdk", line 429, in get_content_length
    return int(meta.getheader('Content-Length'))
TypeError: int() argument must be a string or a number, not 'NoneType'
```

Which seems to correlate to this recent change: https://github.com/juj/emsdk/commit/fd087c100da863752d5a892b7b7cecfdb0523731#diff-fadf99b8a6bd0f70987e30f153eb9b44R429

The full build log can be seen here (warning there is a lot of build output that may hang your browser while it loads):
https://ci.appveyor.com/project/rajsite/vireosdk/build/1.0.156#L392

Also as can be seen in the above build link the progress bar in emsdk now prints a ton of console output that is not apparent in older usages:
https://ci.appveyor.com/project/rajsite/vireosdk/build/1.0.154#L350

Is there a way to disable the progress output while keeping the other progress messages?

**Comment by rajsite** [comment]
Also is there a way to update to a specific version or release of the emsdk tool when using `emsdk update`?

**Comment by juj** [comment]
Thanks, pushed fixes in https://github.com/juj/emsdk/commit/b2ebcffbbbc2ba64d5697dc5c37fed530bafecda. That should also stop the % counter spam, by detecting when stdout is not connected to an interactive terminal.

To be able to run specific versions of `emsdk`, probably the easiest way is to bootstrap to `emsdk` via `git clone https://github.com/juj/emsdk.git` and check out a particular revision. There does not currently exist a versioning system for `emsdk` itself.

**Comment by rajsite** [comment]
Thanks @juj! :)
