### ISSUE TITLE
Windows 10 64bit : emsdk update does not get version after 1.37.9

### ISSUE THREAD

**Issue by stephassoria** [juj/emsdk#88]
perhaps a duplicate of issue #68 ?

When doing "emsdk update" in the emscripten command prompt, nothing is printed and it seems that the command do nothing and just exit. 
Then when doing "emsdk list", the last version of the sdk found (in precompiled, or from source, or nightly) is 1.37.9 (the one activated on my PC). 
On another PC, "emsdk update" / "emsdk list" show versions up to 1.37.16 if I remember well...

Stéphane

**Comment by juj** [comment]
This issue was due to https://groups.google.com/forum/#!topic/emscripten-discuss/bKCQxN6Q76Y, an unfortunate bug that broke updates from getting through, so redownloading emsdk is needed to fix.
