### ISSUE TITLE
TypeError: 'cmp' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by GoranM** [juj/emsdk#89]
Full exception:

```
[goran@arch emsdk]$ ./emsdk install --shallow sdk-incoming-64bit binaryen-master-64bit
Fetching all tags from Emscripten Github repository...
Traceback (most recent call last):
  File "./emsdk", line 2247, in <module>
    sys.exit(main())
  File "./emsdk", line 2020, in main
    fetch_emscripten_tags()
  File "./emsdk", line 1488, in fetch_emscripten_tags
    all_tags = sorted(all_tags, cmp=version_compare)
TypeError: 'cmp' is an invalid keyword argument for this function
```

On my linux system (Arch), 'python' refers to python3. It seems that the emsdk script wrongly assumes that 'python' is always going to refer to python2, on every system.

**Comment by Carreau** [comment]
Same things here, edit `emsdk-portable` and add something like that:

```
def cmp_to_key(mycmp):
    'Convert a cmp= function into a key= function'
    class K:
        def __init__(self, obj, *args):
            self.obj = obj
        def __lt__(self, other):
            return mycmp(self.obj, other.obj) < 0
        def __gt__(self, other):
            return mycmp(self.obj, other.obj) > 0
        def __eq__(self, other):
            return mycmp(self.obj, other.obj) == 0
        def __le__(self, other):
            return mycmp(self.obj, other.obj) <= 0
        def __ge__(self, other):
            return mycmp(self.obj, other.obj) >= 0
        def __ne__(self, other):
            return mycmp(self.obj, other.obj) != 0
    return K
if sys.version_info > (3, ):
    import builtins
    def sorted(collection, cmp=None):
        if cmp:
            return builtins.sorted(collection, key=cmp_to_key(cmp))
        return builtins.sorted(collection)
```

There is another `if sys.version_info >= (3,):` near the top so we could do fold it into that.
So far it seem to work, it went as far as building LLVM.

**Comment by GoranM** [comment]
There is no `emsdk-portable`. Do you mean the `emsdk` python script?

I could also just change the shebang, like in this PR: https://github.com/juj/emsdk/pull/60

There also seems to be another open PR for python 3 compatibility ...

Are there any plans to merge those?

**Comment by Carreau** [comment]
> There is no emsdk-portable. Do you mean the emsdk python script?

Yes. `emsdk` sorry it was late when I wrote previsous comment. 

> I could also just change the shebang, like in this PR: #60

Sure, but if you do not have Python2 installed...

>There also seems to be another open PR for python 3 compatibility ...
> Are there any plans to merge those?

I've seen the PR – but it seem old. I came across this issue/repo trying to fill the same bug. Project seem active so I _guess_ it might be merge at some point. I'll attempt to send this as a proper PR at some point if nobody beat me to it.

**Comment by GoranM** [comment]
> Project seem active

A lot of issues and pull requests that have been open for months, without even a single comment ...

**Comment by MCDELTAT** [comment]
I'd appreciate some further thoughts onto this, I ran into this bug as well on my system. Python 2 is EOL is 2020, so I think we should all just start thinking about moving on. 

Since I had python2 for all the other libraries that haven't upgraded, I just did #60 and changed line 1 to ```python2```

**Comment by juj** [comment]
Fixed in https://github.com/juj/emsdk/commit/04d4f7dbeff886d4bdb38671dda35dd9b21d634e.

**Comment by juj** [comment]
> Python 2 is EOL is 2020, so I think we should all just start thinking about moving on.

Python 2 EOL date does not matter. What matters is the share of users on different OSes that we support. Once users do no longer have Python 2 and have Python 3, then Python 3 will take precedence.

I'll be happy to change the shebang at https://github.com/juj/emsdk/blob/master/emsdk#L1 from `#!/usr/bin/env python` to `#!/usr/bin/env python2` once Apple ships python under `python2` and not `python` and the market share for older OS X versions are low enough to not matter. Currently OS X takes precedence over Linux variants because that is where most of our users are. That being said, the approach has been to write `emsdk` to be dual executable under both Python 2 and 3, though there may be some bugs. The above commit fixes up this issue.

> EDIT 2: I also has a python error with emrun as detailed in the Getting Started section of the website. I had to open up emrun and also modify that to explicitly call python2.

Emrun is probably currently not Python 3 compatible. Fixes there are welcome.

> EDIT 3: Just realized the compiled files also totaled 25.7 GB for me.... is there no way to shrink that? We should probably warn about that before compiling.

This comes from debug information format in `incoming` branch when built under `Debug` or `RelWithDebInfo`. The `incoming` branch is generally for developers. Try `emsdk install latest`, which is the recommended way for getting stable releases, or `emsdk install --build=Release sdk-incoming-64bit` to build a non-debug-info version of LLVM which will be smaller.

**Comment by GoranM** [comment]
> Try `emsdk install latest`, which is the recommended way for getting stable releases

According to the official webassembly site (http://webassembly.org/getting-started/developers-guide/), we need to build from source if we want to have WASM support, so `emsdk install latest` is not an option in that case.

Is WASM support going to be a part of stable any time soon?

> or `emsdk install --build=Release sdk-incoming-64bit` to build a non-debug-info version of LLVM which will be smaller.

It would be nice if that was mentioned on the official site.

> We should probably warn about that before compiling.

Yeah, that would be useful.

**Comment by juj** [comment]
Actually, `emsdk install latest` does work with Wasm, we have been bundling it to precompiled toolchains for some time now. Authored https://github.com/WebAssembly/website/pull/104 to update the documentation.

**Comment by GoranM** [comment]
Oh, man, if only I knew beforehand. I have a fairly under-powered machine, so it basically took me a better part of the day to compile from source.

Well, at least I'll be able to redeem the disk space.

Anyway, I really appreciate the help, and I hope they accept your PR as soon as possible, so that others won't have to go through all this.

PS: Your commit seems to be failing their automated Travis CI build process. I don't know if they expect you to fix that, or if that's something they need to be involved in, but, in either case, I hope it's resolved quickly.
