### ISSUE TITLE
emsdk update fails on Windows due to loaded Python DLLs

### ISSUE THREAD

**Issue by segevfiner** [juj/emsdk#90]
```
C:\emsdk>emsdk update
Downloading: C:/emsdk/zips/emsdk_windows_update.zip from https://s3.amazonaws.com/mozilla-games/emscripten/packages/emsdk_windows_update.zip, 21277300 Bytes
 Unpacking 'C:/emsdk/zips/emsdk_windows_update.zip' to 'C:/emsdk'
Unzipping file 'C:/emsdk/zips/emsdk_windows_update.zip' failed due to reason: [Errno 13] Permission denied: '\\\\?\\C:\\emsdk\\python\\2.7.5.3_64bit\\DLLs\\_hashlib.pyd'
Fetching all tags from Emscripten Github repository...
Done. 105 tagged releases available, latest is 1.37.18.
... trimmed ...
```

emsdk tries to overwrite DLLs that it's own process currently has loaded. Sadly Windows doesn't allow that (Unlike most Unix derived systems). emsdk just continues updating afterwards (The code doesn't check for errors in updating emsdk. Maybe on purpose. [emsdk.py:1534-1547](https://github.com/juj/emsdk/blob/239f40821c1f21f89dbb755f50d594e2e12fc3f3/emsdk#L1534-L1547)).

This happened to me using the portable emsdk distribution: [emsdk-1.35.0-portable-64bit.zip](https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-1.35.0-portable-64bit.zip), linked from here: [Download and install — Emscripten 1.37.10 documentation](https://kripken.github.io/emscripten-site/docs/getting_started/downloads.html).

I'm using Windows 10.0.15063.

**Comment by juj** [comment]
Thanks, this was a bug that `emsdk_windows_update.zip` should not contain python 2.7.5.3_64bit, but it was creeping to the update after we migrated to autodeploying the builds. Fixed in the above commit.
