### ISSUE TITLE
<urlopen error unknown url type: https> when install on mac

### ISSUE THREAD

**Issue by l3ve** [juj/emsdk#92]
run: ./emsdk install sdk-incoming-64bit binaryen-master-64bit

I got the error like this：

```
Error downloading URL 'https://s3.amazonaws.com/mozilla-games/emscripten/packages/node-v4.1.1-darwin-x64.tar.gz': <urlopen error unknown url type: https>
```

**Comment by l3ve** [comment]
ok, i solve the problem.
update the python to 2.7.10 and install the ssl then `make` python

**Comment by tocm** [comment]
if upload the python to 3.6 would happen the problem~~~

**Comment by scientistnik** [comment]
in python 2.7.15 problem happen!

**Comment by JesseAbram** [comment]
I ran into this same issue. This solved it https://stackoverflow.com/a/42334357
